{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 8,
			"minor" : 0,
			"revision" : 3,
			"architecture" : "x64",
			"modernui" : 1
		}
,
		"classnamespace" : "box",
		"rect" : [ 945.0, -1114.0, 640.0, 480.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 1,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"style" : "",
		"subpatcher_template" : "",
		"boxes" : [ 			{
				"box" : 				{
					"id" : "obj-7",
					"maxclass" : "newobj",
					"numinlets" : 0,
					"numoutlets" : 2,
					"outlettype" : [ "", "" ],
					"patching_rect" : [ 190.0, 155.0, 94.0, 22.0 ],
					"text" : "fs.novaLCXL a3"
				}

			}
 ],
		"lines" : [  ],
		"parameters" : 		{
			"obj-7::obj-40" : [ "s[13]", "s", 0 ],
			"obj-7::obj-39" : [ "s[12]", "s", 0 ],
			"obj-7::obj-38" : [ "s[11]", "s", 0 ],
			"obj-7::obj-37" : [ "s[10]", "s", 0 ],
			"obj-7::obj-49" : [ "s[28]", "s", 0 ],
			"obj-7::obj-32" : [ "s[9]", "s", 0 ],
			"obj-7::obj-50" : [ "s[29]", "s", 0 ],
			"obj-7::obj-119" : [ "live.button[20]", "live.button", 0 ],
			"obj-7::obj-26" : [ "s[8]", "s", 0 ],
			"obj-7::obj-51" : [ "s[30]", "s", 0 ],
			"obj-7::obj-25" : [ "s[7]", "s", 0 ],
			"obj-7::obj-52" : [ "s[31]", "s", 0 ],
			"obj-7::obj-93" : [ "live.button[13]", "live.button", 0 ],
			"obj-7::obj-24" : [ "s[6]", "s", 0 ],
			"obj-7::obj-53" : [ "s[32]", "s", 0 ],
			"obj-7::obj-117" : [ "live.button[18]", "live.button", 0 ],
			"obj-7::obj-94" : [ "live.button[14]", "live.button", 0 ],
			"obj-7::obj-1" : [ "s[16]", "s", 0 ],
			"obj-7::obj-95" : [ "live.button[15]", "live.button", 0 ],
			"obj-7::obj-118" : [ "live.button[19]", "live.button", 0 ],
			"obj-7::obj-85" : [ "live.button[7]", "live.button", 0 ],
			"obj-7::obj-18" : [ "s", "s", 0 ],
			"obj-7::obj-6" : [ "s[18]", "s", 0 ],
			"obj-7::obj-126" : [ "live.button[24]", "live.button", 0 ],
			"obj-7::obj-83" : [ "live.button[6]", "live.button", 0 ],
			"obj-7::obj-7" : [ "s[19]", "s", 0 ],
			"obj-7::obj-82" : [ "live.button[5]", "live.button", 0 ],
			"obj-7::obj-8" : [ "s[20]", "s", 0 ],
			"obj-7::obj-81" : [ "live.button[4]", "live.button", 0 ],
			"obj-7::obj-9" : [ "s[21]", "s", 0 ],
			"obj-7::obj-17" : [ "s[22]", "s", 0 ],
			"obj-7::obj-80" : [ "live.button[3]", "live.button", 0 ],
			"obj-7::obj-43" : [ "s[23]", "s", 0 ],
			"obj-7::obj-42" : [ "s[15]", "s", 0 ],
			"obj-7::obj-41" : [ "s[14]", "s", 0 ],
			"obj-7::obj-46" : [ "s[25]", "s", 0 ],
			"obj-7::obj-47" : [ "s[26]", "s", 0 ],
			"obj-7::obj-86" : [ "live.button[8]", "live.button", 0 ],
			"obj-7::obj-48" : [ "s[27]", "s", 0 ],
			"obj-7::obj-23" : [ "s[5]", "s", 0 ],
			"obj-7::obj-87" : [ "live.button[9]", "live.button", 0 ],
			"obj-7::obj-22" : [ "s[4]", "s", 0 ],
			"obj-7::obj-120" : [ "live.button[21]", "live.button", 0 ],
			"obj-7::obj-88" : [ "live.button[10]", "live.button", 0 ],
			"obj-7::obj-21" : [ "s[3]", "s", 0 ],
			"obj-7::obj-89" : [ "live.button[11]", "live.button", 0 ],
			"obj-7::obj-128" : [ "live.button[26]", "live.button", 0 ],
			"obj-7::obj-20" : [ "s[2]", "s", 0 ],
			"obj-7::obj-90" : [ "live.button[12]", "live.button", 0 ],
			"obj-7::obj-125" : [ "live.button[16]", "live.button", 0 ],
			"obj-7::obj-76" : [ "live.button", "live.button", 0 ],
			"obj-7::obj-19" : [ "s[1]", "s", 0 ],
			"obj-7::obj-5" : [ "s[17]", "s", 0 ],
			"obj-7::obj-79" : [ "live.button[2]", "live.button", 0 ],
			"obj-7::obj-127" : [ "live.button[25]", "live.button", 0 ],
			"obj-7::obj-78" : [ "live.button[1]", "live.button", 0 ],
			"parameterbanks" : 			{

			}

		}
,
		"dependency_cache" : [ 			{
				"name" : "fs.novaLCXL.maxpat",
				"bootpath" : "~/Documents/0_WORKPLACE/max-lib/maxlib-felthiv/controlers",
				"patcherrelativepath" : ".",
				"type" : "JSON",
				"implicit" : 1
			}
 ],
		"autosave" : 0
	}

}
